### ISSUE TITLE
Failed to convert image

### ISSUE THREAD

**Issue by khirasier** [Jampi0n/Skyrim-LoadingScreenGenerator#1]
sometimes an image will fail to be converted to dds, which cancels the entire synthesis meaning i have to remove the image from the folder and run it again, would it be possible to make it continue the synthesis and just give a log at the end of all images failed to be converted and added

**Comment by khirasier** [comment]
System.AggregateException: One or more errors occurred. (Texture conversion failed. No texture file was created.)
 ---> System.IO.IOException: Texture conversion failed. No texture file was created.
   at LoadScreenGen.TextureGen.<>c__DisplayClass2_0.<ProcessTextures>b__0(Int32 i) in C:\Users\khira\AppData\Local\Temp\Synthesis\scw35cbt.wf2\Git\3thqnj1i.fsg\Runner\LoadScreenGen\TextureGen.cs:line 168
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body)
   at LoadScreenGen.TextureGen.ProcessTextures(String sourceDirectory, String[] targetDirectory, Int32[] imageResolution, Boolean includeSubDirs, TextureCompression[] textureCompression) in C:\Users\khira\AppData\Local\Temp\Synthesis\scw35cbt.wf2\Git\3thqnj1i.fsg\Runner\LoadScreenGen\TextureGen.cs:line 117
   at LoadScreenGen.Program.RunPatch(IPatcherState`2 state) in C:\Users\khira\AppData\Local\Temp\Synthesis\scw35cbt.wf2\Git\3thqnj1i.fsg\Runner\LoadScreenGen\Program.cs:line 39
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass12_0`2.<<AddPatch>b__0>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 103
--- End of stack trace from previous location ---
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, Nullable`1 exportKey, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 555
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 453
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass36_0.<<InternalRun>b__1>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 416
Synthesis.Bethesda.Execution.CliUnsuccessfulRunException: Error running solution patcher
   at Synthesis.Bethesda.Execution.Patchers.Running.Solution.SolutionPatcherRunner.Run(RunSynthesisPatcher settings, CancellationToken cancel) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Patchers\Running\Solution\SolutionPatcherRunner.cs:line 55
   at Synthesis.Bethesda.Execution.Patchers.Running.Solution.SolutionPatcherRun.Run(RunSynthesisPatcher settings, CancellationToken cancel) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Patchers\Running\Solution\SolutionPatcherRun.cs:line 57
   at Synthesis.Bethesda.Execution.Running.Runner.RunAPatcher.Run(IGroupRun groupRun, PatcherPrepBundle prepBundle, CancellationToken cancellation, Nullable`1 sourcePath, RunParameters runParameters) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Running\Runner\RunAPatcher.cs:line 70

**Comment by Jampi0n** [comment]
I never encountered this problem, but I pushed a fix that just logs the errors as you described.
If the problem appears again, you will have a warning with more information, but the patcher will continue.
Does it happen with specific images? If so, can you upload one? It could be a special format that's not supported yet.

**Comment by khirasier** [comment]
it is specific images as far as i can tell but they are all just regular jpg's

**Comment by khirasier** [comment]
https://imgur.com/a/ymXVlh0 heres some of the images it cant seem to convert
